name: places_resnet152_stage1
print_freq: 100
workers: 48
log_dir: 'logs'
model_dir: 'ckps'


# dataset & model setting
dataset: 'places'
data_path: '/mnt/places365/'
num_classes: 365
imb_factor: null
backbone: 'resnet152_fe'
resume: ''
head_class_idx:
  - 0
  - 131
med_class_idx:
  - 131
  - 288
tail_class_idx:
  - 288
  - 365


# distributed training
deterministic: False
distributed: False
gpu: null
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
dist_backend: 'nccl'
multiprocessing_distributed: False

# Difficulty-Net
lamda: 0.3
hidden_layer: 512
diff_net_lr: 1e-3
diff_net_wd: 1e-4



# Train
mode: 'stage1'
lr: 0.01
batch_size: 128
weight_decay: 5e-4
num_epochs: 30
momentum: 0.9
cos: False





